version: '3.8'

services:
  backend:
    build:
      context: ./relogio-back
    ports:
      - "5000:5000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./relogio-front
    ports:
      - "80:80"
